"""EcoRadar Data Source Manager.

The manager is the mandatory source-control gate for every EcoRadar project.
It centralizes source registration, availability auditing, connector status and
indicator completeness before any indicator, diagnosis, recommendation or
reporting step is allowed to run.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Any

from ecoradar.sources.availability import (
    DEFAULT_CONFIG,
    ensure_mandatory_preflight,
    load_data_sources,
    run_data_availability_check,
)


@dataclass(frozen=True)
class DataSourceManagerResult:
    """Paths and summary generated by the Data Source Manager."""

    data_availability_report: str
    data_availability_markdown: str
    connectors_status_report: str
    indicators_completeness_report: str
    summary: dict[str, Any]


class DataSourceManager:
    """Stable API for EcoRadar source registration and auditing."""

    def __init__(self, config_path: str | Path = DEFAULT_CONFIG) -> None:
        self.config_path = Path(config_path)
        self.config = load_data_sources(self.config_path)

    def source_catalogue(self) -> dict[str, Any]:
        """Return the central EcoRadar source catalogue."""

        return self.config

    def flattened_sources(self) -> list[dict[str, Any]]:
        """Return every source enriched with its block id/name."""

        rows: list[dict[str, Any]] = []
        for block in self.config.get("blocks", []):
            for source in block.get("sources", []):
                row = dict(source)
                row["block_id"] = block.get("id")
                row["block_name"] = block.get("name")
                rows.append(row)
        return rows

    def audit_project(self, project_root: str | Path) -> DataSourceManagerResult:
        """Audit all registered sources and generate mandatory reports."""

        result = run_data_availability_check(project_root, config_path=self.config_path)
        return DataSourceManagerResult(
            data_availability_report=result["data_availability_report"],
            data_availability_markdown=result["data_availability_markdown"],
            connectors_status_report=result["connectors_status_report"],
            indicators_completeness_report=result["indicators_completeness_report"],
            summary=result["summary"],
        )

    def ensure_ready_for_indicators(self, project_root: str | Path) -> None:
        """Require mandatory source reports before running indicators."""

        ensure_mandatory_preflight(project_root)

    def sources_requiring_credentials(self) -> list[dict[str, Any]]:
        """Return registered sources with credential requirements."""

        return [source for source in self.flattened_sources() if source.get("requires_credentials")]

    def manual_or_legal_sources(self) -> list[dict[str, Any]]:
        """Return sources that require manual handling or legal authorization."""

        rows: list[dict[str, Any]] = []
        for source in self.flattened_sources():
            access_type = str(source.get("access_type", "")).lower()
            connector = str(source.get("responsible_connector", "")).lower()
            if "manual" in access_type or "legal" in access_type or connector.startswith("blocked_"):
                rows.append(source)
        return rows


def run_data_source_manager(
    project_root: str | Path = "projectes/Alinya",
    *,
    config_path: str | Path = DEFAULT_CONFIG,
) -> DataSourceManagerResult:
    """Convenience function used by scripts and tests."""

    return DataSourceManager(config_path).audit_project(project_root)
