"""Central EcoRadar indicator definitions.

This module defines the indicator catalogue only. It does not calculate scores,
recommend management actions, or interpret project data.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Iterable


@dataclass(frozen=True)
class IndicatorDefinition:
    """Static definition of an EcoRadar indicator."""

    code: str
    name: str
    thematic_block: str
    objective: str
    required_data: tuple[str, ...]
    data_sources: tuple[str, ...]
    calculation_method: str
    valuation_scale: str
    confidence_level: str
    limitations: tuple[str, ...]
    associated_recommendations: tuple[str, ...]
    calculation_status: str = "not_implemented"


def _indicator(
    code: str,
    name: str,
    block: str,
    objective: str,
    required_data: Iterable[str],
    sources: Iterable[str],
    method: str,
    scale: str,
    recommendations: Iterable[str],
    limitations: Iterable[str] = (),
) -> IndicatorDefinition:
    return IndicatorDefinition(
        code=code,
        name=name,
        thematic_block=block,
        objective=objective,
        required_data=tuple(required_data),
        data_sources=tuple(sources),
        calculation_method=method,
        valuation_scale=scale,
        confidence_level="pendent_dades; alta si totes les fonts requerides son verificades i actuals",
        limitations=tuple(limitations)
        or (
            "Definicio de biblioteca: el calcul real encara no esta implementat.",
            "La puntuacio 0-100 s'ha de validar amb dades locals i criteri tecnic.",
        ),
        associated_recommendations=tuple(recommendations),
    )


INDICATORS: tuple[IndicatorDefinition, ...] = (
    _indicator(
        "ECO_COB_01",
        "Diversitat de cobertes",
        "Cobertes i mosaic del paisatge",
        "Mesurar la varietat de cobertes del sol dins l'area d'estudi.",
        ("cobertes del sol", "superficie per classe"),
        ("ICGC Cobertes del Sol", "MCSC CREAF"),
        "Calcular diversitat de classes i heterogeneitat espacial de cobertes.",
        "0 = coberta molt homogenea; 100 = mosaic molt divers i equilibrat.",
        ("Afavorir mosaic agroforestal on la simplificacio sigui alta.",),
    ),
    _indicator(
        "ECO_COB_02",
        "Percentatge de coberta forestal",
        "Cobertes i mosaic del paisatge",
        "Mesurar quin percentatge de l'espai es forestal.",
        ("cobertes del sol", "classes forestals"),
        ("ICGC Cobertes del Sol", "MCSC CREAF"),
        "Superficie forestal / superficie total.",
        "0 = sense coberta forestal; 100 = coberta forestal dominant.",
        ("Relacionar la coberta forestal amb continuitat, refugi climatic i combustible.",),
    ),
    _indicator(
        "ECO_COB_03",
        "Percentatge de prats, pastures i herbassars",
        "Cobertes i mosaic del paisatge",
        "Mesurar la disponibilitat d'espais oberts herbacis.",
        ("cobertes del sol", "classes de prat, pastura i herbassar"),
        ("ICGC Cobertes del Sol", "MCSC CREAF", "treball de camp"),
        "Superficie d'espais oberts herbacis / superficie total.",
        "0 = absencia d'espais oberts; 100 = alta disponibilitat d'espais oberts.",
        ("Prioritzar manteniment de prats i herbassars d'interes.",),
    ),
    _indicator(
        "ECO_COB_04",
        "Percentatge agricola",
        "Cobertes i mosaic del paisatge",
        "Mesurar el pes dels conreus dins l'espai.",
        ("parcel.les agricoles", "tipus de cultiu", "cobertes agricoles"),
        ("SIGPAC", "Mapa de cultius", "ICGC Cobertes del Sol"),
        "Superficie agricola / superficie total.",
        "0 = sense agricultura; 100 = agricultura dominant.",
        ("Detectar oportunitats de gestio agroecologica i mosaic agricola.",),
    ),
    _indicator(
        "ECO_COB_05",
        "Continuitat de masses forestals",
        "Cobertes i mosaic del paisatge",
        "Mesurar grans superficies forestals continues sense discontinuïtats.",
        ("cobertes forestals", "discontinuïtats", "geometria de masses"),
        ("ICGC Cobertes del Sol", "habitats", "Sentinel", "camp"),
        "Identificar components forestals continus i calcular-ne mida i connexio.",
        "0 = masses petites o molt interrompudes; 100 = grans masses continues.",
        ("Crear o conservar discontinuïtats compatibles amb biodiversitat.",),
        ("No equival per si sol a risc d'incendi final.",),
    ),
    _indicator(
        "ECO_HAB_01",
        "Riquesa d'habitats",
        "Habitats i valor ecologic",
        "Comptar el nombre d'habitats diferents dins l'area.",
        ("codi d'habitat", "superficie d'habitat"),
        ("Cartografia d'habitats Generalitat",),
        "Comptar codis d'habitat unics presents dins el limit.",
        "0 = baixa riquesa; 100 = alta riquesa d'habitats.",
        ("Orientar seguiment cap a habitats rars o poc representats.",),
    ),
    _indicator(
        "ECO_HAB_02",
        "Presencia d'HIC",
        "Habitats i valor ecologic",
        "Mesurar percentatge o superficie d'habitats d'interes comunitari.",
        ("COD_HIC", "superficie d'HIC"),
        ("Cartografia d'habitats Generalitat", "HIC Generalitat"),
        "Superficie HIC / superficie total i llista de codis HIC presents.",
        "0 = sense HIC; 100 = alta proporcio d'HIC.",
        ("Prioritzar conservacio i evitar impactes sobre HIC.",),
    ),
    _indicator(
        "ECO_HAB_03",
        "Habitats prioritaris",
        "Habitats i valor ecologic",
        "Detectar habitats prioritaris segons Directiva Habitats.",
        ("HIC_PRIOR", "superficie d'habitats prioritaris"),
        ("Cartografia d'habitats Generalitat",),
        "Identificar i sumar superficies amb marca d'HIC prioritari.",
        "0 = sense habitats prioritaris; 100 = alta presencia relativa.",
        ("Aplicar criteris de maxima prudencia en zones prioritaries.",),
    ),
    _indicator(
        "ECO_HAB_04",
        "Habitats sensibles",
        "Habitats i valor ecologic",
        "Identificar habitats especialment vulnerables.",
        ("codis d'habitat", "tipologia sensible", "camp opcional"),
        ("Cartografia d'habitats Generalitat", "treball de camp"),
        "Classificar habitats en categories sensibles segons llista tecnica EcoRadar.",
        "0 = sense habitats sensibles detectats; 100 = alta presencia o concentracio.",
        ("Evitar actuacions agressives i planificar seguiment especific.",),
    ),
    _indicator(
        "ECO_HAB_05",
        "Potencial de restauracio d'habitats",
        "Habitats i valor ecologic",
        "Detectar zones degradades o simplificades amb potencial de millora.",
        ("cobertes", "habitats", "teledeteccio", "observacions de camp"),
        ("ICGC Cobertes del Sol", "habitats", "Sentinel", "camp"),
        "Combinar senyals de degradacio, simplificacio i oportunitat d'intervencio.",
        "0 = baix potencial; 100 = alt potencial de restauracio.",
        ("Prioritzar restauracio on el benefici ecologic esperat sigui alt.",),
        ("Requereix validacio de camp per evitar falsos positius.",),
    ),
    _indicator(
        "ECO_VEG_01",
        "Vigor vegetal NDVI",
        "Vegetacio i teledeteccio",
        "Mesurar verdor i activitat fotosintetica.",
        ("NDVI", "data imatge", "nuvols"),
        ("Copernicus / Sentinel",),
        "Calcular estadistics NDVI dins l'area i per coberta si escau.",
        "0 = vigor molt baix; 100 = vigor molt alt.",
        ("Localitzar zones de baixa activitat vegetal per revisio.",),
    ),
    _indicator(
        "ECO_VEG_02",
        "Humitat de vegetacio NDMI",
        "Vegetacio i teledeteccio",
        "Mesurar contingut d'humitat de la vegetacio.",
        ("NDMI", "data imatge", "nuvols"),
        ("Copernicus / Sentinel",),
        "Calcular estadistics NDMI i detectar valors baixos.",
        "0 = humitat molt baixa; 100 = humitat alta.",
        ("Prioritzar seguiment de zones amb estres hidric.",),
    ),
    _indicator(
        "ECO_VEG_03",
        "Aigua superficial / humitat NDWI",
        "Vegetacio i teledeteccio",
        "Detectar presencia o influencia d'aigua.",
        ("NDWI", "cursos d'aigua", "zones humides"),
        ("Copernicus / Sentinel", "ACA/ICGC hidrografia"),
        "Calcular NDWI i creuar-lo amb elements hidrologics.",
        "0 = senyal d'aigua molt baix; 100 = senyal d'aigua alt.",
        ("Conservar zones humides, riberes i basses detectades.",),
    ),
    _indicator(
        "ECO_VEG_04",
        "Anomalia de vegetacio",
        "Vegetacio i teledeteccio",
        "Comparar NDVI/NDMI actual amb anys anteriors.",
        ("series temporals NDVI", "series temporals NDMI"),
        ("Copernicus / Sentinel",),
        "Restar valor actual respecte mitjana o mediana historica comparable.",
        "0 = anomalia negativa severa; 100 = anomalia positiva o recuperacio clara.",
        ("Investigar causes de deteriorament o validar recuperacions.",),
    ),
    _indicator(
        "ECO_VEG_05",
        "Zones de baixa resposta vegetal",
        "Vegetacio i teledeteccio",
        "Detectar sectors amb valors baixos persistents.",
        ("NDVI multitemporal", "NDMI", "cobertes", "camp"),
        ("Copernicus / Sentinel", "cobertes", "camp"),
        "Identificar pixels o poligons amb resposta baixa recurrent.",
        "0 = baixa resposta generalitzada; 100 = resposta vegetal adequada.",
        ("Separar roquissars naturals de degradacio o sobrepastura.",),
    ),
    _indicator(
        "ECO_CLIM_01",
        "Temperatura superficial mitjana",
        "Temperatura superficial i resiliencia climatica",
        "Mesurar temperatura superficial del sol i cobertes.",
        ("LST", "data captura"),
        ("Copernicus LST",),
        "Calcular temperatura superficial mitjana dins l'area.",
        "0 = temperatura molt alta; 100 = temperatura baixa o moderada.",
        ("Contextualitzar vulnerabilitat a calor.",),
    ),
    _indicator(
        "ECO_CLIM_02",
        "Punts calents",
        "Temperatura superficial i resiliencia climatica",
        "Detectar zones amb temperatura superficial elevada.",
        ("LST", "cobertes", "topografia"),
        ("Copernicus LST", "cobertes", "DEM"),
        "Identificar percentils alts de LST i agrupar zones calentes.",
        "0 = molts punts calents; 100 = pocs punts calents.",
        ("Prioritzar ombra, restauracio o reduccio de sol nu on sigui compatible.",),
    ),
    _indicator(
        "ECO_CLIM_03",
        "Refugis climatics",
        "Temperatura superficial i resiliencia climatica",
        "Detectar zones que mantenen temperatures mes baixes.",
        ("LST", "NDMI", "NDVI", "orientacio", "pendent", "coberta forestal", "aigua"),
        ("Copernicus", "DEM", "cobertes", "hidrografia"),
        "Combinar baixa LST, humitat, ombra potencial, coberta i proximitat a aigua.",
        "0 = baix potencial de refugi; 100 = alt potencial de refugi climatic.",
        ("Conservar riberes, fondalades, boscos frescals i ombra.",),
    ),
    _indicator(
        "ECO_CLIM_04",
        "Estres termic de la vegetacio",
        "Temperatura superficial i resiliencia climatica",
        "Detectar vegetacio vulnerable a sequera i canvi climatic.",
        ("LST", "NDMI", "NDVI", "anomalia temporal"),
        ("Copernicus",),
        "Combinar LST alta amb NDMI baix i NDVI baix o en descens.",
        "0 = estres termic alt; 100 = estres baix.",
        ("Prioritzar seguiment i mesures de retencio d'aigua.",),
    ),
    _indicator(
        "ECO_CLIM_05",
        "Vulnerabilitat climatica",
        "Temperatura superficial i resiliencia climatica",
        "Prioritzar actuacions de restauracio, ombra i reduccio d'estres.",
        ("LST", "orientacio", "pendent", "humitat", "coberta vegetal", "aigua"),
        ("Copernicus", "DEM", "cobertes", "hidrografia"),
        "Index compost a partir de calor, exposicio, baixa humitat i manca d'aigua.",
        "0 = vulnerabilitat baixa; 100 = vulnerabilitat alta.",
        ("Orientar restauracio climatica i conservacio de refugis.",),
    ),
    _indicator(
        "ECO_FAU_01",
        "Riquesa d'especies citades",
        "Fauna i biodiversitat",
        "Comptar especies registrades en fonts publiques i dades propies.",
        ("registres d'especies", "font", "data"),
        ("GBIF", "iNaturalist", "dades propies EcoRadar"),
        "Comptar noms cientifics unics, separant recents, historics i dubtosos.",
        "0 = baixa riquesa citada; 100 = alta riquesa citada.",
        ("Prioritzar mostreig si la riquesa aparent es baixa o esbiaixada.",),
    ),
    _indicator(
        "ECO_FAU_02",
        "Especies indicadores",
        "Fauna i biodiversitat",
        "Detectar especies associades a bon estat ecologic.",
        ("registres d'especies", "llista d'especies indicadores"),
        ("GBIF", "iNaturalist", "camp", "llistes EcoRadar"),
        "Creuar registres amb cataleg d'indicadores per grup funcional.",
        "0 = sense indicadores detectades; 100 = alta presencia d'indicadores.",
        ("Protegir microhabitats i condicions associades a especies indicadores.",),
    ),
    _indicator(
        "ECO_FAU_03",
        "Especies protegides o d'interes",
        "Fauna i biodiversitat",
        "Marcar especies amb valor legal o de conservacio.",
        ("registres d'especies", "llistes legals o de conservacio"),
        ("GBIF", "iNaturalist", "camp", "catalegs oficials"),
        "Creuar taxons amb llistes de proteccio i interes.",
        "0 = sense especies d'interes detectades; 100 = alta concentracio o rellevancia.",
        ("Evitar impactes i prioritzar zones sensibles.",),
        ("No substituir una avaluacio legal especifica.",),
    ),
    _indicator(
        "ECO_FAU_04",
        "Especies invasores",
        "Fauna i biodiversitat",
        "Detectar presencia d'especies invasores.",
        ("registres d'especies", "llista d'invasores"),
        ("GBIF", "iNaturalist", "camp", "catalegs oficials"),
        "Creuar taxons amb llistes d'especies invasores.",
        "0 = alta presencia d'invasores; 100 = sense invasores detectades.",
        ("Prioritzar control, seguiment i prevencio d'expansio.",),
    ),
    _indicator(
        "ECO_FAU_05",
        "Buit d'informacio faunistica",
        "Fauna i biodiversitat",
        "Mesurar grups poc mostrejats o zones sense dades.",
        ("registres per grup", "data", "distribucio espacial"),
        ("GBIF", "iNaturalist", "camp"),
        "Avaluar absencia de registres recents, grups infrarepresentats i buits espacials.",
        "0 = informacio molt incompleta; 100 = cobertura d'informacio bona.",
        ("Planificar treball de camp en grups o zones infrarepresentades.",),
    ),
    _indicator(
        "ECO_ANT_01",
        "Densitat de camins i pistes",
        "Pressio humana i usos",
        "Calcular km de camins per km2.",
        ("xarxa de camins", "area"),
        ("OpenStreetMap", "ICGC", "dades del gestor"),
        "Longitud total de camins i pistes / superficie.",
        "0 = densitat molt baixa; 100 = densitat molt alta.",
        ("Gestionar accessos o restaurar camins redundants si cal.",),
    ),
    _indicator(
        "ECO_ANT_02",
        "Intensitat potencial d'us public",
        "Pressio humana i usos",
        "Detectar zones potencialment frequentades.",
        ("senders", "aparcaments", "miradors", "refugis", "zones recreatives", "camp"),
        ("OpenStreetMap", "Strava si autoritzat", "dades de camp", "gestors"),
        "Combinar proximitat i densitat d'elements d'us public amb fonts d'intensitat autoritzades.",
        "0 = baixa intensitat potencial; 100 = alta intensitat potencial.",
        ("Orientar ordenacio d'us public i seguiment de zones frequentades.",),
        ("Strava no es pot usar fins que hi hagi acces autoritzat.",),
    ),
    _indicator(
        "ECO_ANT_03",
        "Zones tranquil.les",
        "Pressio humana i usos",
        "Detectar arees allunyades de camins, aparcaments i infraestructures.",
        ("camins", "aparcaments", "infraestructures", "distancies"),
        ("OpenStreetMap", "ICGC", "gestors"),
        "Calcular distancia a accessos i infraestructures i classificar zones allunyades.",
        "0 = poca tranquil.litat; 100 = alta tranquil.litat potencial.",
        ("Conservar zones tranquil.les per fauna sensible.",),
    ),
    _indicator(
        "ECO_ANT_04",
        "Pressio agraria",
        "Pressio humana i usos",
        "Avaluar pressio potencial associada a agricultura.",
        ("superficie agricola", "tipus de cultiu", "proximitat a habitats sensibles"),
        ("SIGPAC", "mapa de cultius", "habitats"),
        "Combinar superficie, tipus de cultiu i proximitat a elements sensibles.",
        "0 = pressio agraria baixa; 100 = pressio agraria alta.",
        ("Promoure gestio agroecologica en zones de contacte sensible.",),
    ),
    _indicator(
        "ECO_ANT_05",
        "Pressio ramadera",
        "Pressio humana i usos",
        "Detectar sobrepastura, infrapastura i oportunitats de gestio.",
        ("pastures", "punts d'aigua", "tancats", "carrega ramadera", "camp"),
        ("treball de camp", "dades del gestor", "cartografia de pastures"),
        "Indicador manual o mixt basat en signes de camp i dades de carrega.",
        "0 = desequilibri ramader alt; 100 = pressio compatible amb objectius.",
        ("Ajustar carrega o redistribuir pastura si hi ha evidencies.",),
    ),
    _indicator(
        "ECO_ANT_06",
        "Infraestructures i barreres",
        "Pressio humana i usos",
        "Detectar elements que fragmenten o dificulten moviment ecologic.",
        ("carreteres", "linies electriques", "edificacions", "tanques", "canals", "pistes"),
        ("OpenStreetMap", "ICGC", "xarxa electrica verificada", "gestors"),
        "Cartografiar barreres i estimar densitat o proximitat a habitats sensibles.",
        "0 = barreres altes; 100 = baixa fragmentacio per infraestructures.",
        ("Prioritzar permeabilitzacio o minimitzacio d'impactes.",),
    ),
    _indicator(
        "ECO_INC_01",
        "Continuitat de combustible",
        "Incendis i resiliencia del paisatge",
        "Mesurar continuitat forestal i matollar.",
        ("cobertes forestals", "matollars", "habitats", "Sentinel", "camp"),
        ("cobertes", "habitats", "Sentinel", "camp"),
        "Detectar masses continues de vegetacio combustible.",
        "0 = baixa continuitat; 100 = continuitat molt alta.",
        ("Identificar zones on introduir mosaic sense perjudicar valors sensibles.",),
    ),
    _indicator(
        "ECO_INC_02",
        "Mosaic protector",
        "Incendis i resiliencia del paisatge",
        "Valorar presencia de discontinuïtats que poden dificultar propagacio.",
        ("conreus", "prats", "pastures", "roquissars", "zones humides", "franges naturals"),
        ("cobertes", "habitats", "hidrografia", "camp"),
        "Mesurar proporcio i distribucio de discontinuïtats naturals o agroforestals.",
        "0 = mosaic protector feble; 100 = mosaic protector alt.",
        ("Conservar o recuperar discontinuïtats d'alt valor ecologic.",),
    ),
    _indicator(
        "ECO_INC_03",
        "Vulnerabilitat topografica al foc",
        "Incendis i resiliencia del paisatge",
        "Combinar pendent, orientacio i continuitat del vessant.",
        ("DEM", "pendent", "orientacio", "unitats de vessant"),
        ("ICGC DEM",),
        "Derivar topografia i classificar exposicio potencial a propagacio.",
        "0 = vulnerabilitat topografica baixa; 100 = vulnerabilitat alta.",
        ("Integrar topografia en planificacio forestal i accessos.",),
    ),
    _indicator(
        "ECO_INC_04",
        "Humitat potencial del combustible",
        "Incendis i resiliencia del paisatge",
        "Estimar humitat potencial de vegetacio i combustible.",
        ("NDMI", "NDWI", "LST", "orientacio", "proximitat a aigua"),
        ("Copernicus", "DEM", "hidrografia"),
        "Combinar humitat remota, temperatura, exposicio i distancia a aigua.",
        "0 = humitat potencial baixa; 100 = humitat potencial alta.",
        ("Prioritzar mesures de conservacio d'humitat i refugis frescals.",),
    ),
    _indicator(
        "ECO_INC_05",
        "Prioritat de gestio forestal compatible amb biodiversitat",
        "Incendis i resiliencia del paisatge",
        "Decidir on actuar primer sense malmetre valors ecologics.",
        ("risc potencial", "habitats sensibles", "biodiversitat", "connectivitat", "possibilitat d'actuacio"),
        ("cobertes", "habitats", "fauna", "connectivitat", "camp"),
        "Index compost futur que combina necessitat de gestio i restriccions ecologiques.",
        "0 = baixa prioritat compatible; 100 = alta prioritat compatible.",
        ("Prioritzar actuacions amb retorn ecologic i baix conflicte de conservacio.",),
        ("No es pot calcular abans de validar capes de risc, biodiversitat i camp.",),
    ),
    _indicator(
        "ECO_AIG_01",
        "Densitat de cursos d'aigua",
        "Aigua i hidrologia ecologica",
        "Mesurar rius, torrents i barrancs.",
        ("xarxa hidrografica", "area"),
        ("ICGC", "ACA"),
        "Longitud de cursos d'aigua / superficie.",
        "0 = densitat molt baixa; 100 = densitat alta.",
        ("Prioritzar proteccio de riberes i torrents d'interes.",),
    ),
    _indicator(
        "ECO_AIG_02",
        "Punts d'aigua",
        "Aigua i hidrologia ecologica",
        "Detectar fonts, basses, abeuradors, zones humides i surgencies.",
        ("punts d'aigua", "tipologia", "estat"),
        ("cartografia", "camp", "gestor"),
        "Inventariar i classificar punts d'aigua dins l'area.",
        "0 = molt pocs punts d'aigua; 100 = alta disponibilitat.",
        ("Mantenir punts d'aigua amb valor per fauna i connectivitat.",),
    ),
    _indicator(
        "ECO_AIG_03",
        "Valor ecologic de punts d'aigua",
        "Aigua i hidrologia ecologica",
        "Valorar naturalitat i interes ecologic dels punts d'aigua.",
        ("naturalitat", "amfibis", "vegetacio de ribera", "temporalitat", "pressions", "qualitat visual"),
        ("treball de camp",),
        "Indicador de camp amb fitxa tecnica i criteris comuns.",
        "0 = valor ecologic baix; 100 = valor ecologic alt.",
        ("Restaurar o protegir punts d'aigua amb potencial.",),
    ),
    _indicator(
        "ECO_AIG_04",
        "Connectivitat hidrica",
        "Aigua i hidrologia ecologica",
        "Mesurar connexio entre cursos, basses, riberes i zones humides.",
        ("xarxa hidrografica", "zones humides", "punts d'aigua", "cobertes"),
        ("ACA", "ICGC", "camp"),
        "Avaluar proximitat i continuitat espacial d'elements hidrics.",
        "0 = connectivitat baixa; 100 = connectivitat alta.",
        ("Millorar connexio de riberes, basses i zones humides.",),
    ),
    _indicator(
        "ECO_AIG_05",
        "Vulnerabilitat hidrica",
        "Aigua i hidrologia ecologica",
        "Combinar manca d'aigua, calor, baixa humitat vegetal i pressions.",
        ("aigua", "LST", "NDMI", "pressio ramadera", "clima"),
        ("ACA/ICGC", "Copernicus", "camp"),
        "Index compost futur de deficit hidric i pressions associades.",
        "0 = vulnerabilitat baixa; 100 = vulnerabilitat alta.",
        ("Prioritzar retencio d'aigua i reduccio de pressions.",),
    ),
    _indicator(
        "ECO_CON_01",
        "Connectivitat d'habitats naturals",
        "Connectivitat ecologica",
        "Mesurar continuitat entre habitats naturals.",
        ("cobertes", "habitats", "infraestructures"),
        ("cobertes", "habitats", "infraestructures"),
        "Avaluar continuitat espacial d'habitats naturals i seminaturals.",
        "0 = connectivitat baixa; 100 = connectivitat alta.",
        ("Conservar corredors i reduir interrupcions.",),
    ),
    _indicator(
        "ECO_CON_02",
        "Fragmentacio",
        "Connectivitat ecologica",
        "Mesurar divisio del paisatge per infraestructures, usos intensius o discontinuïtats.",
        ("infraestructures", "cobertes", "hàbitats", "mida de fragments"),
        ("OpenStreetMap", "ICGC", "cobertes", "habitats"),
        "Calcular mida, nombre i aillament de fragments naturals.",
        "0 = fragmentacio baixa; 100 = fragmentacio alta.",
        ("Prioritzar restauracio de continuitat i passos permeables.",),
    ),
    _indicator(
        "ECO_CON_03",
        "Corredors ecologics potencials",
        "Connectivitat ecologica",
        "Detectar riberes, carenes, mosaics i zones de pas.",
        ("riberes", "carenes", "mosaic", "cobertes", "barreres"),
        ("hidrografia", "DEM", "cobertes", "infraestructures"),
        "Modelitzar zones de permeabilitat potencial sense establir prioritat final.",
        "0 = baix potencial de corredor; 100 = alt potencial.",
        ("Protegir i reforçar corredors potencials validats.",),
    ),
    _indicator(
        "ECO_CON_04",
        "Barreres ecologiques",
        "Connectivitat ecologica",
        "Detectar elements que dificulten moviment de fauna o fluxos ecologics.",
        ("carreteres", "tanques", "canals", "urbanitzacio", "linies i grans pistes"),
        ("OpenStreetMap", "ICGC", "gestors", "camp"),
        "Inventariar barreres i classificar-ne severitat potencial.",
        "0 = poques barreres; 100 = moltes barreres o molt severes.",
        ("Proposar permeabilitzacio o reduccio d'impactes en fases futures.",),
    ),
    _indicator(
        "ECO_CAMP_01",
        "Qualitat ecologica observada",
        "Treball de camp i validacio experta",
        "Valorar naturalitat, complexitat, pressions reals i potencial de millora.",
        ("fitxa de camp", "observador", "certesa", "comentari tecnic"),
        ("treball de camp EcoRadar",),
        "Indicador manual del tecnic amb escala comuna de qualitat ecologica.",
        "0 = qualitat observada baixa; 100 = qualitat observada alta.",
        ("Usar criteri expert per ajustar recomanacions finals.",),
    ),
    _indicator(
        "ECO_CAMP_02",
        "Microhabitats",
        "Treball de camp i validacio experta",
        "Registrar microhabitats rellevants.",
        ("fusta morta", "cavitats", "roquissars", "murs", "basses", "talussos", "arbres vells", "rastres"),
        ("treball de camp EcoRadar",),
        "Comptar i qualificar microhabitats presents per unitat o zona.",
        "0 = microhabitats escassos; 100 = microhabitats abundants i diversos.",
        ("Conservar microhabitats clau i evitar neteges excessives.",),
    ),
    _indicator(
        "ECO_CAMP_03",
        "Coherencia entre dades remotes i realitat",
        "Treball de camp i validacio experta",
        "Comparar resultats automatics amb observacio de camp.",
        ("indicadors automatics", "observacions de camp", "validacio experta"),
        ("EcoRadar Analysis Engine", "treball de camp"),
        "Mesurar concordança o discrepancia entre capes remotes i observacio.",
        "0 = baixa coherencia; 100 = alta coherencia.",
        ("Revisar models i prioritats quan hi hagi discrepancia.",),
    ),
)


_INDICATORS_BY_CODE = {indicator.code: indicator for indicator in INDICATORS}


def list_indicators() -> tuple[IndicatorDefinition, ...]:
    """Return all indicator definitions in library order."""

    return INDICATORS


def get_indicator(code: str) -> IndicatorDefinition:
    """Return one indicator by code."""

    try:
        return _INDICATORS_BY_CODE[code]
    except KeyError as exc:
        known = ", ".join(sorted(_INDICATORS_BY_CODE))
        raise KeyError(f"Unknown indicator '{code}'. Known indicators: {known}") from exc


def indicators_by_block(block: str) -> tuple[IndicatorDefinition, ...]:
    """Return all indicators belonging to a thematic block."""

    return tuple(indicator for indicator in INDICATORS if indicator.thematic_block == block)
